spring.application.name=RecipeMatcher

spring.config.import=optional:file:./secrets/postgresql.properties

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=recipe_matcher
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never